name: 'PageSpeed Insight Report Action'
description: 'Generate PageSpeed Insights reports straight to Github'
author: 'Colby Fayock <hello@colbyfayock.com>'

inputs:
  url:
    description: 'URL to audit'
    required: true
    default: 'https://www.google.com'
  outputDirectory:
    description: 'Directory to add reports'
    required: true
    default: './reports'

runs:
  using: 'node12'
  main: 'dist/index.js'