name: 'Lighthouse Report'
description: 'Generate a new audit report with Lighthouse'
author: 'Colby Fayock'

inputs:
  url:
    description: 'URL to audit'
    required: true
    default: 'https://www.google.com'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}