name: 'Lighthouse Report'
description: 'Generate a new audit report with Lighthouse'
author: 'Colby Fayock'

inputs:
  url:
    description: 'URL to audit'
    required: true
    default: 'https://www.google.com'
  outputDirectory:
    description: 'Directory to add reports'
    required: true
    default: 'reports'

runs:
  using: 'node12'
  main: 'dist/index.js'